name: Build Android APK
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # <-- PASTIKAN INI v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4 # <-- PASTIKAN INI v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4 # <-- PASTIKAN INI v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk