# Nama alur kerja Anda, akan muncul di tab "Actions" di GitHub
name: Build Android APK

# Pemicu: Alur kerja ini akan berjalan setiap kali ada push ke branch 'main' atau 'master'
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# Pekerjaan yang akan dilakukan
jobs:
  build:
    # Menggunakan server virtual Ubuntu versi terbaru
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Mengunduh kode dari repositori Anda ke server virtual
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Menyiapkan lingkungan Java Development Kit (JDK) versi 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Langkah 3: Memberikan izin eksekusi pada gradlew
      # (Penting agar server bisa menjalankan perintah build)
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Langkah 4: Menjalankan perintah build untuk membuat APK Release
      # Ini sama seperti menekan tombol "Build APK" di Android Studio
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # Langkah 5: Mengunggah APK yang sudah jadi sebagai artefak
      # Anda akan bisa mengunduh file ini dari halaman hasil build di GitHub
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk # Nama artefak
          path: app/build/outputs/apk/release/app-release-unsigned.apk
          # Kita menggunakan app-release-unsigned.apk karena kita belum setup signing key