# Nama alur kerja Anda
name: Build Android APK

# Pemicu
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# Pekerjaan yang akan dilakukan
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- PERBAIKAN DI SINI ---
      # Langkah 2: Menyiapkan lingkungan JDK versi 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # <-- UBAH NILAI INI DARI '11' MENJADI '17'
          distribution: 'temurin'
          cache: gradle

      # Langkah 3: Memberikan izin eksekusi pada gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Langkah 4: Menjalankan perintah build
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # Langkah 5: Mengunggah APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk